export { useUser } from "../redux/ducks/login/index.js"
export { usePost } from "../redux/ducks/jobpost/index.js"
export { useRegister } from "../redux/ducks/register/index"
export { useJobs } from "../redux/ducks/viewjobposts/index.js"
export { useProfile } from "../redux/ducks/rprofile/index"
export { useProfilefree } from "../redux/ducks/fprofile/index"
